### ISSUE TITLE
Problems with performing custom verification  

### ISSUE THREAD

**Issue by OriCat101** [mosparo/mosparo#122]
Hi

First of all, sorry for the many issues.

I am currently working on a backed client for Mosparo, written in ColdFusion, that will eventually be made into a plugin for [MasaCMS](https://github.com/MasaCMS/MasaCMS). I am currently working on the verification of the Form data but I'm having some issues with the Auth header.

I am generating the auth header as described in the [docs](https://documentation.mosparo.io/docs/api/verification#verify).
```ColdFusion
  /**
   * Generates the authorization header for the API call.
   *
   * @param formData The data struct to be used in generating the header.
   */
  private void function getAuthorizationHeader(
    required struct formData,
    string publicKey = variables.publicKey,
    string privateKey = variables.privateKey
  ) {
    local.apiEndpoint = "/api/v1/verification/verify";
    local.hash = lCase(hmac(local.apiEndpoint & serializeJSON(arguments.formData), getPrivateKey(), 'HmacSHA256'));

    variables.authHeader = "#getPublicKey()#:#local.hash#";
  }
```
If I plug the example values from the [example](https://documentation.mosparo.io/docs/api/verification#example) page into this function I get the same header as the [example](https://documentation.mosparo.io/docs/api/verification#example):
`QqfBxsmOfIMw0-uVNnRVdDlMUZdLpTG1xo0yyifyLrI:3bdd385caa53e3da76a8dcbfcaa0d9f4e04d8c189fab03ba41383deea236b2d3`

Despite all of that I keep getting the following response:
```JSON
{
	"error":true,
	"errorMessage":"Authorization header invalid."
}
```

I just don't know what to do since I have done everything that the dec asks from me and I have been on this issue since the last 4 days. In the screenshot below you will find all the values that could be useful for debugging. 
All forms of help are welcome :3
![image](https://github.com/mosparo/mosparo/assets/63188591/2f00bdff-499c-406a-a09a-d7879b014034)

Also, all my code is available in [this](https://github.com/OriCat101/mosparo-cf-client) repo.

Kind regards,
Ori

**Comment by zepich** [comment]
Hi @OriCat101 

Thank you very much for your question and your work integrating mosparo into MasaCMS!

I think that's, for once, a very easy question... :) I saw this message before, so I know exactly what it is... Long story short: the documentation is wrong...

The Authorization header should look like this:

```
Authorization: [base64 of <publicKey>:<signature>]
```

So, for the example in the documentation:

```
Authorization: UXFmQnhzbU9mSU13MC11Vk5uUlZkRGxNVVpkTHBURzF4bzB5eWlmeUxySTozYmRkMzg1Y2FhNTNlM2RhNzZhOGRjYmZjYWEwZDlmNGUwNGQ4YzE4OWZhYjAzYmE0MTM4M2RlZWEyMzZiMmQzCgo=
```

The code for this error message is located here: https://github.com/mosparo/mosparo/blob/master/src/Subscriber/ProjectSubscriber.php#L97

I also saw this error message when I developed the C# example, but I didn't remember that it was incorrect in the documentation (since I used the PHP API client as an example and forgot to encode it to base64).

As far as I understand your code (I never worked with ColdFusion, to be honest), you're assigning the two values directly to the Authorization header without encoding it to base64.

I'm sorry for the trouble you had with the incorrect documentation! I will update the documentation today evening.

Please let me know if that solves the problem or if you have any other issues!

Kind regards,

zepich

**Comment by OriCat101** [comment]
Hoi @zepich 

Thanks for the fast response.
So, adding a quick toBase64() solved my issue with the Authorization.

Now I'm just getting an error saying my request was invalid.
Since the chances of my code just being bad are pretty high, I just wanted to ask if the rest of the documentation is correct?

Kind regards,
Ori

**Comment by OriCat101** [comment]
Hi @zepich 

> So you have to switch the variable you give to the `getAuthorizationHeader` method. Instead of `variables.signedForm`, you should use `local.requestData`

Unfortunately this did not fix my issue neither did it give a different error message. :(



> please tell me your public and private keys

You can find both keys in my code at line [31](https://github.com/OriCat101/mosparo-cf-client/blob/main/scripts/Gateway.cfc#L31).

Kind regards,
Ori

**Comment by zepich** [comment]
Hi @OriCat101 

Okay, perfect, thank you very much for your update.

I will simulate the request locally.

Can you tell me the signature it generates in the `GetAuthorizationHeader` method and the content which is sent to the `hmac` method in line [156](https://github.com/OriCat101/mosparo-cf-client/blob/main/scripts/Gateway.cfc#L156)? 

(so just the output of this code: `getApiEndpoint() & serializeJSON(arguments.formData)`)

Thank you very much!

Kind regards,

zepich

**Comment by OriCat101** [comment]
Hi @zepich 

Ty for all your effort 

> Can you tell me the signature it generates in the `GetAuthorizationHeader` method and the content which is sent to the `hmac` method in line [156](https://github.com/OriCat101/mosparo-cf-client/blob/main/scripts/Gateway.cfc#L156)?

So, the signature it generates is the following (without pub key & converting it to base64):
`5d3c097726c17baaa8332ea70a29740e9adb3cf15a9c29448b5051b632259c81`

And the data I pass into to the function is:
```JSON
{
  "submitToken": "64nVAXHqo0BFRq_CuiES_ggX6SVGB2XoDSffbECIHzA",
  "validationSignature": "92be461c04b8e6a86af0800f2804437e2e5d394d8e6ffdcf7dcd1443abdbd4d3",
  "formSignature": "413c020b326b282114afb879ee3020c4c489967754b707927a8ee6f810640471",
  "formData": {
    "firstname": "1e454bf83a9c6c4d5f9cf21b56b2150a0ada5058fe9e5e2bdf07e0cac70830d9"
  }
}
```
I hope this is what you need, since I'm not 100% sure I understood you correctly.

Kind regards,
Ori

**Comment by OriCat101** [comment]
Hi @zepich 

Oh, okay, here u go, this is everything I pass into hmac:
```
/api/v1/verification/verify{"submitToken":"64nVAXHqo0BFRq_CuiES_ggX6SVGB2XoDSffbECIHzA","validationSignature":"92be461c04b8e6a86af0800f2804437e2e5d394d8e6ffdcf7dcd1443abdbd4d3","formSignature":"413c020b326b282114afb879ee3020c4c489967754b707927a8ee6f810640471","formData":{"firstname":"1e454bf83a9c6c4d5f9cf21b56b2150a0ada5058fe9e5e2bdf07e0cac70830d9"}}
```

I hope this is what you needed :3

Kind regards,
Ori

**Comment by zepich** [comment]
Hi @OriCat101 

Thank you very much. That's perfect.

So, the good thing first: your code builds the signatures perfectly. I have the same signature as you with the PHP client, so that's not the problem.

But I guess I found the problem now - your last commit to your repository was the hint... :)

The API expects the request data in the body as JSON. As far as I can tell, you add multiple body parameters, but only one will probably work (I guess). I don't know exactly the documentation of the `http` and `httpparam` functionality, but I found this documentation here: https://helpx.adobe.com/coldfusion/cfml-reference/coldfusion-tags/tags-g-h/cfhttpparam.html

(Sorry if that's the wrong documentation)

Adobe says you do not need the `name` attribute for the `body` type. Ultimately, this means you should provide only one `body` param. As a value, you put the request data as JSON encoded. So, something like that:

```coldfusion
http charset='UTF-8'
method='POST'
result='local.result'
url='#getHost()##getApiEndpoint()#'
{
  // httpparam type='header' name='Accept'         value='application/json';
  httpparam type='header' name='Authorization' value='#variables.authHeader#';
  httpparam type='header' name='Content-Type' value='application/json';
  httpparam type="body" value="#serializeJSON(local.requestData)#";
}
```

Additionally, you should set the Content-Type header to `application/json`.

Examples:
- JavaScript: https://github.com/mosparo/js-api-client/blob/master/src/Client.js#L74
- Python: https://github.com/mosparo/python-api-client/blob/master/mosparo_api_client/Client.py#L74

Please let me know if that solves the problem or if you still get the same error.

Please let me know if there is better documentation about the `http` functionality.

Kind regards,

zepich

**Comment by zepich** [comment]
Side note: The issue in the documentation is fixed. Thank you for your pull request!

**Comment by OriCat101** [comment]
Hi @zepich 

Thx for all your time and effort. 
I've modified my request like you told me, which has resulted in massive progress.
The submissions are now showing up in the Mosparo backend🥳.

But I'm still having some problems with the client.
My request get authenticated and all the tokens seem to be correct. But I am still unable to verify my submissions.
```json
{
  "valid": false,
  "verificationSignature": "",
  "verifiedFields": {
    "firstname": "invalid"
  },
  "issues": [
    {
      "name": "firstname",
      "message": "Field not valid."
    }
  ]
}
```
The response I get is not changing depending on what I input so I think that the issue still is my (trashy) code. 

![image](https://github.com/mosparo/mosparo/assets/63188591/0f9a5a48-d209-4bd4-a880-a0a90de138ae)



> Please let me know if there is better documentation about the `http` functionality.

ColdFusion and good docs... Good CF documentation basically doesn't exist. However my fav page to go for documentation is [cfdocs.org](cfdocs.org), so this it what I'd suggest on using.


Kind regards,
Ori

**Comment by zepich** [comment]
Hi @OriCat101 

Awesome! Thank you very much for your feedback!

> Thank you so much for all your help. Thanks to you I finally did it and have a working backend client :3 I am so relieved to finally be done with this, after working on this on and of for the last two weeks.

You're more than welcome! Thank you for using mosparo and helping to integrate mosparo into more systems and languages!

Wait, you already worked on that issue for two weeks? 😮 If you have any other problem in the future with mosparo, please let me know earlier! Thanks to your issue, we found two mistakes in the documentation, and I will add two new ideas for future developments (1. adding a debug mode in which the API will help you to find the issue with more information than now, and 2. adding a developer mode in which you can simulate the verification process in the UI to understand better where the problem appears), so it was very good that you created the issue!

I wish you a nice day and looking forward to your next issue... 😄 

Kind regards,

zepich
